services:
  - type: web
    name: amazon-tv-scraper
    runtime: node
    buildCommand: npm install
    startCommand: node amazonTvScraper.js
    envVars:
      - key: NODE_VERSION
        value: "18.0.0"
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"
      - key: PUPPETEER_EXECUTABLE_PATH
        value: "/usr/bin/google-chrome"
